// This file was generated by the "svnrev" utility
// You should not modify it manually, as it may be re-generated.
//
// $Revision: 6478 $
// $Date: 2014-7-8 $
//
// Licensed under the Apache License, Version 2.0 (the License); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an AS IS BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
//


using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SeeMS")]
[assembly: AssemblyDescription("A visualization, annotation, and processing tool for mass spectrometry data.")]
[assembly: AssemblyCompany("Vanderbilt University")]
[assembly: AssemblyProduct("SeeMS")]
[assembly: AssemblyCopyright("Copyright © Vanderbilt University 2014")]
[assembly: AssemblyVersion("3.0.6478")]
[assembly: AssemblyFileVersion("3.0.6478")]
